apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      containers:
        - name: scheduler
          image: artmann/guvnor:latest
          imagePullPolicy: Always
          args: ['scheduler:start']
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: url
            - name: DB_DATABASE
              value: "guvnor-production"
