apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: worker
  template:
    metadata:
      labels:
        app: worker
    spec:
      containers:
        - name: worker
          image: artmann/guvnor:latest
          imagePullPolicy: Always
          args: ['worker:start']
          env:
            - name: REGION
              value: north-america-west
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: database
                  key: url
            - name: DB_DATABASE
              value: "guvnor-production"
